### ISSUE TITLE
As a user, I can create a personal tenant, so that I can see my own tenant space.

### ISSUE THREAD

**Issue by jonasclaes** [jonasclaes/as-built#2]
Acceptance criteria:
- Tenant is created for this user based on their UID
- User is redirected to their own tenant
- Contains a owner UID
- Contains a mapping in a separate `permissions` table
  - `user uid`
  - `tenant uid`
  - `permission name` (ex. `project:create`; `project:edit`; `project:view`, `client:create`, ... )

**Comment by SeppeStroobants** [comment]
many to many - users => tenant
